#explorando métodos 

print('=== desafio 4 ===')
n1 = input('Digite qualquer coisa: ')
print(f'Você escreveu {n1}')
print('Você escreveu o tipo: ', type(n1))
print('Ele é alfanúmerico? ', n1.isalnum())
print('Ele é númerico? ', n1.isnumeric())
print('Ele é alfabético? ', n1.isalpha())
print('Ele está em letras minúsculas? ', n1.islower())
print('Ele está em letras maiúsculas? ', n1.isupper())
print('Ele é imprimível? ', n1.isprintable())
print('Ele é um espaço? ', n1.isspace())
print('Ele é um dígito? ', n1.isdigit())
print('Ele está capitalizado? ', n1.istitle())
